# Generated by Django 4.2.3 on 2023-07-12 00:08

from django.db import migrations, models
import game.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board', models.JSONField(default=game.models.initial_board)),
                ('current_player', models.CharField(default='X', max_length=1)),
            ],
        ),
    ]
